
DEBUG_FLAGS=-O0 -g -std=c++11 -I../include -I../../quickcheck/quickcheck

cactus_basic: cactus-basic.cpp ../include/cactus-basic.hpp
	g++ $(DEBUG_FLAGS) cactus-basic.cpp -o cactus-basic

clean:
	rm -f cactus-basic
